"use client";

import { useCallback, useEffect, useState } from "react";

export type PushSupportState = "unsupported" | "denied" | "default" | "granted";

// Converts the VAPID public key (URL-safe base64, as generated by
// web-push) into the Uint8Array shape PushManager.subscribe expects.
const urlBase64ToUint8Array = (base64String: string) => {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");
  const rawData = window.atob(base64);
    return Uint8Array.from(rawData.split("").map((c) => c.charCodeAt(0)));
};

// Drives the "enable push notifications" button: reports current
// permission state, and on request registers the service worker,
// prompts for permission, subscribes, and posts the subscription to the
// server. Deliberately does none of this automatically on mount - asking
// for notification permission should always follow a deliberate click.
export const usePushNotifications = () => {
  const [state, setState] = useState<PushSupportState>("default");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    if (typeof window === "undefined") return;
    if (!("Notification" in window) || !("serviceWorker" in navigator) || !("PushManager" in window)) {
      setState("unsupported");
      return;
    }
    setState(Notification.permission as PushSupportState);
  }, []);

  const enable = useCallback(async () => {
    const publicKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;
    if (!publicKey) {
      console.log("NEXT_PUBLIC_VAPID_PUBLIC_KEY is not set - push notifications are disabled");
      return false;
    }

    setBusy(true);
    try {
      const permission = await Notification.requestPermission();
      setState(permission as PushSupportState);
      if (permission !== "granted") return false;

      const registration = await navigator.serviceWorker.register("/sw.js");
      const readyRegistration = await navigator.serviceWorker.ready.catch(() => registration);

      const subscription = await readyRegistration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(publicKey),
      });

      await fetch("/api/push/subscribe", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(subscription.toJSON()),
      });

      return true;
    } catch (err) {
      console.log("failed to enable push notifications", err);
      return false;
    } finally {
      setBusy(false);
    }
  }, []);

  const disable = useCallback(async () => {
    setBusy(true);
    try {
      const registration = await navigator.serviceWorker.getRegistration();
      const subscription = await registration?.pushManager.getSubscription();
      if (subscription) {
        await fetch("/api/push/unsubscribe", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ endpoint: subscription.endpoint }),
        });
        await subscription.unsubscribe();
      }
    } catch (err) {
      console.log("failed to disable push notifications", err);
    } finally {
      setBusy(false);
    }
  }, []);

  return { state, busy, enable, disable };
};
